### ISSUE TITLE
`DeleteTestEnvironment` method defunct

### ISSUE THREAD

**Issue by philwhiteuk** [ewilde/go-runscope#1]
We're having problems deleting environments that are associated with a test using the `DeleteTestEnvironment()` method.

Looks like the problem is that Runscope's API only supports deleting an environment a single way: https://www.runscope.com/docs/api/environments#delete

In this case the endpoint should be `/buckets/<bucket_key>/environments/<environment_id>` (same as `DeleteSharedEnvironment()` method)

**Comment by philwhiteuk** [comment]
@ewilde suggested solution https://github.com/ewilde/go-runscope/pull/2 (breaking change)

**Comment by ewilde** [comment]
closed by #2
