### ISSUE TITLE
Issues mocking types (e.g. runscope.Client)

### ISSUE THREAD

**Issue by pagnmickie** [ewilde/go-runscope#7]
@ewilde 

I'm trying to write unit tests for my code, which uses your library. I'd like to mock the objects provided by your library but can't seem to, since there are no interfaces defined.

For instance, I defined a mockClient struct but can't pass it to functions expecting a `*runscope.Client:`

`./runscope_util_test.go:24:22: cannot use &mc (type *mockClient) as type *runscope.Client in argument to GetBucket`

The definition of GetBucket:
`func GetBucket(client *runscope.Client, bucketName string) *runscope.Bucket {}`

How can I mock Client and various other types provided by your library?

Thanks!

**Comment by pagnmickie** [comment]
Any thoughts on this @ewilde ?

**Comment by ewilde** [comment]
hey @pagnmickie a guess an interface makes sense and would allow you to mock calls to the api. I'm happy to help, would you like to work on this and raise a PR?

**Comment by pagnmickie** [comment]
@ewilde I will take a stab at it for sure! I'm just learning Golang so I will definitely want input!

**Comment by ewilde** [comment]
@pagnmickie :+1: my first thoughts would be something along the lines of:

1. Create an interface
```golang
type ClientAPI interface{
    CreateTest(test *Test) (*Test, error)
    ReadTest(test *Test) (*Test, error) 
    ReadTests(bucketKey string) ([]*Test, error)
   // ... etc. .. for every function in type Client
}
```

Then in your code reference ClientAPI and in your test code it will be easy to mock the interface

**Comment by pagnmickie** [comment]
@ewilde Not done testing on my end but I was able to successfully mock the client for unit tests. My branch: https://github.com/ewilde/go-runscope/compare/master...pagnmickie:interface

Let me know what you think 👍

**Comment by pagnmickie** [comment]
Resolved with PR attached
